# Generated by Django 4.1.4 on 2023-02-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='type',
            field=models.CharField(default='tweet', max_length=10),
            preserve_default=False,
        ),
    ]
