# Generated by Django 4.1.4 on 2023-02-25 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_meta_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meta',
            old_name='type',
            new_name='content_type',
        ),
    ]
