# Generated by Django 4.1.3 on 2022-11-05 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('likes', models.IntegerField(default=0)),
                ('posted_date', models.DateTimeField()),
                ('comments', models.ManyToManyField(blank=True, to='tweets.comment')),
                ('posted_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tweets.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.CharField(max_length=255)),
                ('likes', models.IntegerField(default=0)),
                ('posted_date', models.DateTimeField()),
                ('comments', models.ManyToManyField(blank=True, to='tweets.comment')),
                ('posted_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tweets.userprofile')),
            ],
        ),
    ]
