# Generated by Django 4.1.3 on 2022-11-06 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_comment_tweet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='posted_by',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 14, 22, 59, 5367), verbose_name='posted date'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='posted_by',
            field=models.ManyToManyField(to='tweets.userprofile'),
        ),
    ]
