# Generated by Django 4.1.4 on 2023-01-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0008_comment_likes_count_remove_comment_likes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
