# Generated by Django 4.1.4 on 2023-01-09 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0009_delete_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='posted_by',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='posted_by',
            new_name='author',
        ),
    ]
