# Generated by Django 4.1.4 on 2023-02-24 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
        ('tweets', '0012_rename_tweet_tweet_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='posted_date',
        ),
        migrations.AddField(
            model_name='tweet',
            name='meta',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='meta.meta'),
            preserve_default=False,
        ),
    ]
